### ISSUE TITLE
Test bug? Price for both orders is the same.

### ISSUE THREAD

**Issue by mrc** [GaryHughes/Exchange#2]
https://github.com/GaryHughes/Exchange/blob/4c2ff4f16f2384e43eefe16b2e31c1c1aa23bc92/Part%201/cpp_solution/exchange_tests.cpp#L59-L77

I think the intent of the test is to check that an incoming order executes at the book price, but both orders have the same price.

**Comment by GaryHughes** [comment]
Right you are, fixed.
